### ISSUE TITLE
Create Build Process for Distributing App

### ISSUE THREAD

**Issue by chalkers** [thingsSDK/flasher.js#16]
Create a build process for distributing applications.

npm run dist-windows
npm run dist-mac
npm run dist-linux

**Comment by craigsdennis** [comment]
Going to attempt to use [Electron Builder](https://github.com/electron-userland/electron-builder)

**Comment by chalkers** [comment]
We're using Electron Packager now on branch - packager.

**Comment by chalkers** [comment]
Have Mac signing working.
Have Windows installer working.
Next Windows signing (waiting on cert)

**Comment by chalkers** [comment]
Have linux working now. Also fixed #19 while I was at it :)
