### ISSUE TITLE
Adding a new device LYT8266

### ISSUE THREAD

**Issue by stephenkeep** [thingsSDK/flasher.js#36]
Thanks so much for releasing this software. I have successfully installed it on a Witty and its running well.

What do we need to do to add new devices to the list of supported devices? It would be fantastic to have Espruino on the LYT8266.

https://authometion.com/shop/en/home/13-lyt8266.html

Thanks

**Comment by chalkers** [comment]
Hey @stephenkeep - have you got a lyt8266 to test it with?

**Comment by stephenkeep** [comment]
Hi @chalkers,

I don't have one but if its possible then im happy to get one!

Cheers

Steve
