### ISSUE TITLE
Needs 32 bit support

### ISSUE THREAD

**Issue by jkgibson** [thingsSDK/flasher.js#41]
Errors in setup log when trying to run on Windows 10, 32-bit.

**Comment by Delfairen** [comment]
It would be great if we could just let 32 bit windows quietly go into the
woods and die. This has been dragging out too long. Even the Microsoft
devices with less than 4GB out ran even come with 64 but versions of
Windows installed. Hell even 32 bit programs run on 64 bit windows without
issues 95% of the time.

**Comment by chalkers** [comment]
I've got the binaries, putting the code and release up shortly. Thanks for being my guinea pig @jkgibson
