### ISSUE TITLE
Support for ESP32 - any plans?

### ISSUE THREAD

**Issue by wilberforce** [thingsSDK/flasher.js#54]
The python tool has been upgraded to support the ESP32 and 8266

https://github.com/espressif/esptool

Any plans to update flasher.js?

**Comment by chalkers** [comment]
Definitely. We were waiting for the other tools to stabilize before taking action. @craigsdennis looked at the esptool last night and is looking to start work on the next iteration.

**Comment by devdudeio** [comment]
ESP32 support would be awesome

**Comment by craigsdennis** [comment]
Probably time to tackle this with async/await right?

**Comment by hanfengcan** [comment]
Have there been any fresh developments of the project?

**Comment by bart** [comment]
Any updates?

**Comment by devdudeio** [comment]
Project seems to be dead last commit is 8 months ago

**Comment by bart** [comment]
Yes, unfortunately :(

**Comment by chalkers** [comment]
We'll be back!

**Comment by rlech** [comment]
Why is the issue closed when there is no answer is the initial question ?
