### ISSUE TITLE
mac 1.1.0 not flashing espruino to esp8266 on macOS 10.13.4

### ISSUE THREAD

**Issue by givehug** [thingsSDK/flasher.js#59]
Flasher indicates that flash was successful, but web Ide doesn't see it. Can't connect with thingssdk-cli neither. Tried few different firmware versions.

<img width="507" alt="screen shot 2018-05-19 at 1 59 57 am" src="https://user-images.githubusercontent.com/10002142/40261719-faa4ff16-5b0a-11e8-9738-43ad18c9dee3.png">

Flashing with esptool.py works.

```
esptool.py --port /dev/cu.SLAB_USBtoUART --baud 115200 write_flash --flash_freq 80m --flash_mode dio --flash_size 32m 0x0000 "boot_v1.6.bin" 0x1000 espruino_esp8266_user1.bin 0x3FC000 esp_init_data_default.bin 0x3FE000 blank.bin
```

**Comment by chalkers** [comment]
Are you using the 115200 baud rate or 9600? Be sure to use 115200

**Comment by givehug** [comment]
Espruino ide is set to 115200. Flasher only has 'select port' and 'select binaries to flash' options.

Probably related to node-gyp, serialport. Got a lot of errors when installing dependencies. Will look into that. I use node 10.0.0

**Comment by givehug** [comment]
closing as irrelevant
